bankapp/bankapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bankapp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('register/',include('registration.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bankapp/home/urls.py
from django.conf.urls.static import static

from . import views
from django.urls import path, include
app_name='home'

urlpatterns = [
    path('',views.homefn,name='homefn'),
]

bankapp/registration/urls.py
from . import views
from django.urls import path, include
app_name='registration'

urlpatterns = [
    path('',views.registerfn,name='registerfn'),
    path('login/',views.loginfn,name='loginfn'),
    path('logedpage/',views.logfn,name='logfn'),
    path('logout/',views.logout,name='logout'),
    path('accepted/', views.accepted, name='accepted'),
    path('add/', views.PersonCreateView.as_view(), name='person_add'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
]

bankapp/home/models.py
from django.db import models

# Create your models here.

bankapp/home/views.py
from django.shortcuts import render

# Create your views here.
def homefn(request):
    return render(request,'index.html')

bankapp/templates/accepted.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application Status</title>
    <link rel="stylesheet" href="{% static 'css/accepted.css' %}">
</head>
<body>
<div class="card-wrapper">
  <img src="https://acdfm.mindef.gov.bn/PublishingImages/Thank%20you.png">
  <div class="text">
    <div class="title">Your Application Accepted</div>
    <div class="info">
        We will inform you when the account is created. the Debit & Credit cards will send to you at given address.
    </div>
  </div>
  <div class="btn-wrapper">
      <a href="{% url 'home:homefn' %}" ><button class="btn">Back to Home</button></a>
  </div>
</div>
</body>
</html>

bankapp/templates/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create an Account</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">

    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>

</head>
<body>
<div class="container" style="padding-left:20%;padding-right:20%;">

<form method="post" id="personForm" data-cities-url="{% url 'registration:ajax_load_cities' %}" novalidate>
  {% csrf_token %}
  <div class="container">
    <h1 style="color:blue">Account Opening Form</h1>
    <p style="color:blue" >Please fill in this form to create an account.</p>
  {% for i in messages %}
    <h3 style="color:red;">Error: {{i}}</h3>
  {% endfor %}
    <br><hr>
      <div class="row">
      <table>
        <tr>
          <th>
              <div class="col-sm-6 col-md-6 col-6 col-lg-6"></div>
          </th>
          <th>
              <div class="col-sm-6 col-md-6 col-6 col-lg-6"></div>
          </th>
        </tr>
        <tr>
            <td>
    <label><b>NAME:</b></label>
            </td>
            <td>
                {{form.errors.name}}
                {{ form.name }}
            </td>
        </tr>
        <tr>
            <td>
    <label><b>DATE OF BIRTH: </b></label>
            </td>
            <td>{{form.errors.dob}}
                {{ form.dob }}
                <br><br>
            </td>
        </tr>
        <tr>
            <td>
    <label><b>AGE:  </b></label>
            </td>
            <td>{{form.errors.age}}
                {{ form.age }}
                <br><br>
            </td>
        </tr>
        <tr>
            <td>
    <label><b>GENDER:</b></label>
            </td>
            <td>{{form.errors.gender}}
                {{ form.gender }}
                <br><br>
            </td>
        </tr>
        <tr>
            <td>
    <label><b>PHONE NUMBER:</b></label>
            </td>
            <td>{{form.errors.phone}}
    {{ form.phone }}<br><br>
            </td>
        </tr>
        <tr>
            <td>
    <label><b>MAIL ID:</b></label>
            </td>
            <td>{{form.errors.email}}
    {{ form.email }}<br><br>
            </td>
        </tr>
        <tr>
            <td>
        <label><b>ADDRESS:</b></label>
            </td>
            <td>{{form.errors.address}}
    {{ form.address }}<br><br>
            </td>
        </tr>
        <tr>
            <td>
        <label><b>DISTRICT:</b></label>
            </td>
            <td>{{form.errors.district}}
                {{form.district}}
            </td>
        </tr>
        <tr>
            <td>
    <br><br>

        <label><b>BRANCH:</b></label>
            </td>
            <td>

    <br><br>
                {{form.branch}}
            </td>
        </tr>
        <tr>
            <td>
    <br><br>
        <label><b>ACCOUNT TYPE:</b></label>
            </td>
            <td>
                <br><br>{{form.errors.account}}
                {{ form.account }}
            </td>
        </tr>
          <tr></tr>
        <tr>
            <td>
        <label><b>MATERIALS PROVIDE:</b></label>
            </td>
            <td>
        <h3>
                Debit Card: {{ form.debit }}<br><br>
                Credit Card: {{ form.credit }}<br><br>
                Cheque Book: {{ form.cheque }}<br><br>
        </h3>
            </td>
        </tr>
        <tr>
            <td>
    <hr>

                <a href="{% url 'registration:accepted' %}"><button type="submit" class="registerbtn">Register</button></a>
            </td>
      </table>
  </div>
      </div>
</form>

    </div>
    <div class="container signin">
    <a href="{% url 'registration:logout' %}"><button type="button" class="btn btn-danger"> Logout</button></a>
  </div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_district").change(function () {
      var url = $("#personForm").attr("data-cities-url");
      var countryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_branch").html(data);
        }
      });

    });
  </script>

</body>
</html>

bankapp/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN</title>
    <link rel="stylesheet" href="{% static 'css/loginstyles.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
</head>
<body>



<div class="login">
  <h2 class="active"> sign in </h2>

    {% for i in messages %}
        <h3 style="color:red;">Error: {{i}}</h3>
    {% endfor %}
  <form action="###" method="post">
  {% csrf_token %}
    <input type="text" class="text" name="username" placeholder="enter username">
     <span>username</span>

    <br>

    <br>

    <input type="password" class="text"  name="password" placeholder="enter password">
    <span>password</span>
    <br>

    <input type="checkbox" id="checkbox-1-1" class="" />
    <label for="checkbox-1-1">Keep me Signed in</label>

    <button class="signin">
      Sign In
    </button>


    <hr>

    <a href="{% url 'registration:registerfn' %}">New Registration</a>
  </form>

</div>

</body>
</html>

bankapp/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SignUp An Account</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
</head>
<body>
<div class="container" style="width:80%; text-align:center; padding-left:20%">
<form action="#" method="post">
  {% csrf_token %}
  <div class="container">
    <h1>Register</h1>
    <p>Please fill in this form to create an account.</p>
  {% for i in messages %}
    <h3 style="color:red;">Error: {{i}}</h3>
  {% endfor %}
    <br><hr>

    <label><b>Username</b></label>
    <input type="text" placeholder="Enter username" name="username" id="username" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" id="psw" required>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required>
    <hr>

    <button type="submit" class="registerbtn">Register</button>
  </div>

  <div class="container signin">
    <p>Already have an account? <a href="{% url 'registration:loginfn' %}">Sign in</a>.</p>
  </div>
</form>
  </div>
</body>
</html>

bankapp/templates/trial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

  <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>

</head>
<body>
<h2>Person Form</h2>

  <form method="post" id="personForm" data-cities-url="{% url 'registration:ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_p }}

    </table>
    <label><b>MATERIALS PROVIDE:</b></label>

    <button type="submit">Save</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_district").change(function () {
      var url = $("#personForm").attr("data-cities-url");
      var countryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_branch").html(data);
        }
      });

    });
  </script>
</body>
</html>

bankapp/templates/trial2.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}