todoapp/app1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app1 import views
app_name='app1'
urlpatterns = [
    path('',views.fn1,name='fn1'),
    path('delete/<int:id>/',views.deletefn,name='deletefn'),
    path('update/<int:id>/',views.updatefn,name='updatefn'),
    path('list/',views.list.as_view(),name='list'),
    path('detail/<int:pk>/',views.detail.as_view(),name='detail'),
    path('update1/<int:pk>/',views.update.as_view(),name='update'),
    path('delete1/<int:pk>/',views.delete.as_view(),name='delete'),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

todoapp/app1/models.py
from django.db import models

# Create your models here.
class task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.CharField(max_length=250)
    date=models.DateField()

    def __str__(self):
        return self.name

todoapp/app1/forms.py
from django import forms

from app1.models import task


class updateform(forms.ModelForm):
    class Meta:
        model=task
        fields=['name','priority','date']

todoapp/app1/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy

from .forms import updateform
from app1.models import task
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView,DeleteView

def fn1(request):
    var=task.objects.all()
    if request.method=='POST':
        n1=request.POST.get('n')
        p1=request.POST.get('pri')
        d=request.POST.get('date')
        v1=task(name=n1,priority=p1,date=d)
        v1.save()
    return render(request,'home.html',{'k1':var})

def deletefn(request,id):
    if request.method=='POST':
        ta=task.objects.get(id=id)
        ta.delete()
        return redirect('/')
    return render(request,'delete.html')

def updatefn(request,id):
    up=task.objects.get(id=id)
    upform=updateform(request.POST or None,request.FILES,instance=up)
    if upform.is_valid():
        upform.save()
        return redirect('/')
    return render(request,'update.html',{'u':up,'uf':upform})

class list(ListView):
    model=task
    template_name = 'home.html'
    context_object_name = 'k1'

class detail(DetailView):
    model=task
    template_name = 'details.html'
    context_object_name = 'd'

class update(UpdateView):
    model=task
    template_name = 'update.html'
    context_object_name = 'task'
    fields=('name','priority','date')


    def get_success_url(self):
        return reverse_lazy('app1:detail',kwargs={'pk':self.object.id})

class delete(DeleteView):
    model=task
    template_name = 'delete.html'
    success_url = reverse_lazy('app1:fn1')

todoapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
<body style="background-color:lightblue;">
{% block body %}
{% endblock %}
</body>
</html>

todoapp/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    ARE YOU WANT TO DELETE THIS FILE?<br>
    <button type="submit" class="btn btn-danger">confirm</button>
</form>
{% endblock %}

todoapp/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="shadow card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{d.name}}</h5>
                        <p class="card-text">{{d.priority}}</p>
                        <p class="card-text">{{d.date}}</p>
                    </div>
                </div><br>
{% endblock %}

todoapp/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
              {% csrf_token %}
                <div class="form-group" >
                <input type="text" class="form-control" name="n" placeholder="enter your name">
                </div>
                <div class="form-group">
                <input type="text" class="form-control" name="pri" placeholder="enter you priority number">
                </div>
                <div class="form-group" >
                <input type="date" class="form-control" name="date" placeholder="enter date">
                </div>
                <input type="submit" class="btn btn-success">
            </form>
        </div>
            <div class="col-md-6">
                <h3>TASKS CREATED</h3>
                {% for i in k1 %}
                <div class="shadow card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.priority}}</p>
                        <p class="card-text">{{i.date}}</p>
                        <a class="btn btn-danger" href="{% url 'app1:deletefn' i.id %}">Delete</a>
                        <a class="btn btn-warning" href="{% url 'app1:updatefn' i.id %}">Update</a>
                    </div>
                </div><br>
                {% endfor %}
            </div>
    </div>
</div>

{% endblock %}

todoapp/templates/update.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>
{% endblock %}