trialproject1/app1/urls.py
from django.urls import path, include

from . import views
app_name='app1'
urlpatterns = [
    path('',views.fn1,name='fn1'),
    path('test/<int:table1_id>/',views.fn2,name='fn2'),
    path('add/',views.addfn,name='addfn'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
]

trialproject1/trialproject1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app1.urls")),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

trialproject1/app1/models.py
from django.db import models

# Create your models here.
class table1(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    details=models.TextField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

trialproject1/app1/forms.py
from django import forms
from .models import table1

class movieform(forms.ModelForm):
    class Meta:
        model=table1
        fields=['name','desc','details','img']

trialproject1/app1/views.py
import os
from unittest import result

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.files import File

# Create your views here.
from app1.forms import movieform
from app1.models import table1


def fn1(request):
    v1=table1.objects.all()
    context={
        'k1':v1
    }
    return render(request,'h1.html',context)

def fn2(request,table1_id):
   v1=table1.objects.get(id=table1_id)
   return render(request,'details.html',{'k':v1})

def addfn(request):
    if request.method =="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        details=request.POST.get('details')
        img1=request.FILES['imag']
        var1=table1(name=name,desc=desc,details=details,img=img1,)
        var1.save()
    return render(request,'add1.html')

def update(request,id):
    v1=table1.objects.get(id=id)
    v2=movieform(request.POST or None, request.FILES,instance=v1)
    if v2.is_valid():
        v2.save()
        return redirect('/')
    return render(request,'edit.html',{'k1':v2,'k2':v1})

def delete(request,id):
    if request.method=='POST':
      m1=table1.objects.get(id=id)
      m1.delete()
      return redirect('/')
    return render(request,'delete.html')

trialproject1/templates/add1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add data</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name"><br>
    <input type="text" name="desc" placeholder="enter movie description"><br>
    <input type="text" name="details" placeholder="enter movie details"><br>
    <input type="file" name="imag"><br>
    <input type="submit">
</form>
</body>
</html>

trialproject1/templates/delete.html
{% extends 'index.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  ARE YOU WANT TO DELETE THIS FILE?
  <input type="submit">
</form>
{% endblock %}

trialproject1/templates/details.html
{% extends 'index.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{k.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-8">
            <h1>{{k.name}}</h1>
            <h3>{{k.desc}}</h3>
            <a class="btn btn-warning" href="{% url 'app1:update' k.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'app1:delete' k.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

trialproject1/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>update page</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{k1.as_p}}
    <input type="submit">
</form>
</body>
</html>

trialproject1/templates/h1.html
{% extends 'index.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in k1 %}
        <div class="col-md-3">
           <div class="card" style="width:300;" >
              <img src="{{i.img.url}}" class="card-img-top" width="200" height="250"><br>
                 <div class="card-body">
                     <h5 class="card-title">{{i.name}}</h5>
                     <a href="{% url 'app1:fn2' i.id %}" class="btn btn-primary">{{i.name}} :DETAILS</a>
                 </div>
           </div>
        </div>
        {% endfor %}
    </div>
    <a class="btn btn-primary" href="{% url 'app1:addfn' %}">ADD FILMS</a>
</div>


{% endblock %}

trialproject1/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>hello</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">FILM STORE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app1:fn1' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>

    </ul>
  </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>