ecommerce/app1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from app1 import views
app_name='app1'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.proDetail,name='prodCatdetail'),
]


if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from cart import views
app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/', views.cart_item_delete, name='cart_item_delete'),

    ]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

ecommerce/search_app/urls.py
from django.urls import path, include

from . import views
app_name='search_app'

urlpatterns = [
    path('',views.searchresult,name='searchresult'),

    ]

ecommerce/app1/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    img=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('app1:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey('category',on_delete=models.CASCADE)
    img=models.ImageField(upload_to='products',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('app1:prodCatdetail',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/cart/models.py
from django.db import models
from app1.models import product
# Create your models here.
class cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class cartitem(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='cartitem'

    def sub_total(self):
            return self.product.price * self.quantity
    def __str__(self):
            return '{}'.format(self.product)

ecommerce/app1/views.py
from gc import get_objects

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,InvalidPage,EmptyPage

# Create your views here.
from .models import category, product


def allProdCat(request,c_slug=None):
    c_page=None
    products=None

    if c_slug != None:
        c_page=get_object_or_404(category,slug=c_slug)
        products=product.objects.all().filter(category=c_page,available=True)
    else:
        products=product.objects.all().filter(available=True)


    paginator1=Paginator(products,6)
    try:
        page1=int(request.GET.get('page','1'))
    except:
        page1=1
    try:
        prod1=paginator1.page(page1)
    except (EmptyPage,InvalidPage):
        prod1=paginator1.page(paginator1.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products,'pro':prod1})

def proDetail(request,c_slug,p_slug):
    try:
        prod=product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'pro_key':prod,})

ecommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app1.models import product
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
from cart.models import cart,cartitem


def cart_id(request):
    cart1=request.session.session_key
    if not cart1:
        cart1=request.session.create()
    return cart1

def add_cart(request,product_id):
    product1=product.objects.get(id=product_id)

    try:
        cart1=cart.objects.get(cart_id=cart_id(request))
    except cart1.DoesNotExist:
        cart1=cart.objects.create(cart_id=cart_id(request))
        cart1.save()
    try:
        cartitem1=cartitem.objects.get(product=product1,cart=cart1)
        if cartitem1.quantity < cartitem1.product.stock:
            cartitem1.quantity += 1
        cartitem1.save()
    except cartitem.DoesNotExist:
        cartitem1=cartitem.objects.create(product=product1,quantity=1,cart=cart1)
        cartitem1.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart3=cart.objects.get(cart_id=cart_id(request))
        cart_items=cartitem.objects.filter(cart=cart3,active=True)
        for cart_i in cart_items:
            total += (cart_i.product.price * cart_i.quantity)
            counter += cart_i.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items_key=cart_items,total_key=total,counter_key=counter))

def cart_remove(request,product_id):
    cart1=cart.objects.get(cart_id=cart_id(request))
    prod1=get_object_or_404(product,id=product_id)
    cart_item1=cartitem.objects.get(product=prod1,cart=cart1)
    if cart_item1.quantity > 1:
        cart_item1.quantity -= 1
        cart_item1.save()
    else:
        cart_item1.delete()
    return redirect('cart:cart_detail')

def cart_item_delete(request,product_id):
    cart1=cart.objects.get(cart_id=cart_id(request))
    prod1=get_object_or_404(product,id=product_id)
    cart_item1=cartitem.objects.get(product=prod1,cart=cart1)
    cart_item1.delete()
    return redirect('cart:cart_detail')

ecommerce/search_app/views.py
from django.shortcuts import render

# Create your views here.
from app1.models import product
from django.db.models import Q


def searchresult(request):
    prod=None
    query1=None
    if 'q' in request.GET:
        query1=request.GET.get('q')
        prod=product.objects.all().filter(Q(name__contains=query1) | Q(desc__contains=query1))
    return render(request,'search.html',{'que1':query1,'produ':prod})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/custom1.css' %}" rel="stylesheet" >
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body  style="padding-left:5px;padding-right:5px;">
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
 {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>


</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    this is cart page
{% endblock %}
{% block title %}
    cart
{% endblock %}
{% block content %}
{% if not cart_items_key %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Cart is Empty
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'app1:allProdCat' %}">Here</a> to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"> Your shopping Cart</h1>
        <br>
    </div>
</div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for cart_i in cart_items_key %}
                <tr>
                    <td>
                        <a href="cart_i.product.get_absolute_url"><img src="{{cart_i.product.img.url}}" alt="" class="float-left rounded custom_image">
                        </a>
                    </td>
                <td class="text-left">
                    {{cart_i.product.name}}
                    <br>
                    SKU:{{cart_i.product.id}}
                    <br>
                    Price: RS {{cart_i.product.price}}
                    <br>
                    Qty: {{cart_i.quantity}} * {{cart_i}}
                </td>
                <td>
                    RS {{cart_i.sub_total}}
                </td>
                {% if cart_i.quantity < cart_i.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_i.product.id %}" class="custom_a"><i class="fa fa-plus"></i></a>
                    &nbsp; <a href="{% url 'cart:cart_remove' cart_i.product.id %}" class="custom_a"><i class="fa fa-minus"></i></a>
                    &nbsp; <a href="{% url 'cart:cart_item_delete' cart_i.product.id %}" class="custom_icon" ><i class="fa fa-trash"></i></a>
                </td>
                {% else %}
                <td>
                     &nbsp; <a href="{% url 'cart:cart_remove' cart_i.product.id %}" class="custom_a"><i class="fa fa-minus"></i></a>
                    &nbsp; <a href="{% url 'cart:cart_item_delete' cart_i.product.id %}" class="custom_icon" ><i class="fa fa-trash"></i></a>
                </td>
                    {% endif %}
                </tr>

                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td style="font-size:18px;">
                        please review your shopping cart items before proceeding with the order payment
                    </td>
                </tr>
                <tr>
                    <td class="text-left total" >
                        <p>Your Total Amount: RS {{total_key}}</p>

                    <button class="btn btn-danger">Click to Pay</button>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'app1:allProdCat' %}" class="btn btn-primary btn-block my_custom_button">Continue Shopping</a>
            </div>
        </div>
    </div>

{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{category.desc|truncatewords:155}}
  {% else %}
    welcome to ABC Store, where you can buy things
  {% endif %}
{% endblock %}

{% block title %}
  {% if category %}
    {{category.name}}-ABC Store
  {% else %}
    see our new collections
  {% endif %}
{% endblock %}

{% block content %}
  {% if category %}
    <div class="row my_row">
        <div class="mx_auto">
            <P><a href="{% url 'app1:allProdCat' %}">Our Product Collections</a></P>
        </div>
    </div>
  {% endif %}
  <div>
      {% if category %}
        <div>
            <img class="my_image" src="{{category.img.url}}" alt="{{category.name}}">
        </div>
        <br>
        <div>
            <h1 class="text-center font_class"><b>{{category.name}}</b></h1>
            <p class="text-justify my_desc"><b>{{category.desc}}</b></p>
        </div><br>
      <br>
      {% else %}
      <div class="card">
        <div>
            <img class="my_img" src="{% static 'img/banner.jpg' %}" alt="our products" width="1250px">
        </div>
        <br>
        <div>
            <h1 class="our" >Our Product Collections</h1>
            <p class="text-justify my_desc">The suit has framed all the pivotal moments in history. There’s no denying, it’s a powerful piece of clothing – enough to make anyone feel ready to change the world.
We built our suit for the game-changers. Designed for the man ready to take on the world, the slim fit and accentuated shoulders give you the presence you deserve.
Made from the highest-quality fabric, we believe that how you dress has a significant effect on how you’re perceived – we made this suit for the highest quality impact.</p>
<br>
            <br>
        </div>
      </div>
      {% endif %}
  </div>
  <div class="container">
      <div class="row">
          {% for i in pro %}
          <div class="col-md-4 my_card">
          <div class="card" style="width: 300px; height:400px; background-color:#F7DC6F">
          <div>
              <div>
                  <a  href="{{i.get_url}}"><img class="card-img-top my_card_img" src="{{i.img.url}}" alt="{{i.name}}"></a>
              </div>
          </div>
          <div class="card-body">

                  <h2 class="card-title my_card_title">{{i.name}}</h2>
                  <p class="card-text my_card_text">RS: {{i.price}}<h6 style="color:green">10% off</h6></p>
              <div>
                  <a href="#" class="btn btn-primary">BUY NOW</a>
                  <a href="{% url 'cart:add_cart' i.id %}" class="btn btn-warning">ADD TO CART</a>
              </div>

          </div>
          </div>
          </div>
          {% endfor %}
      </div>

      <div class="mx-auto">
          {% if pro.paginator.num_pages > 1 %}
          <hr>
          <div class="text-center">
              {% for p in pro.paginator.page_range %}
              <a href="?page={{p}}" class="btn btn-primary btn-sm {% if pro.number == p %} active {% endif %}">{{p}}</a>
              {% endfor %}<br>
              {{pro}}
          </div>
          {% endif %}
      </div>

  </div>
{% endblock %}

ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;E-COM tech pvt.ltd .All rights are reserved</p>
</div>

ecommerce/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'app1:allProdCat' %}"><img src="{% static 'img/logo2.png' %}" alt="logimage" width="350px" height="200"></a>
    </center>
</header>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app1:allProdCat' %}" >Home</a>
        </li>
        <li class="nav-item dropdown {% if 'app1' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'app1:allProdCat' %}">All Products</a></li>
            {% for cat in link_key %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_c_key > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}">Your cart<i class="fa fa-shopping-cart " >({{item_c_key}})</i></a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a style="padding-left:120px"><b>WELCOME TO E-COM</b></a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" ></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{pro_key.desc | truncatewords:155}}
{% endblock %}
{% block title %}
    {% if category %}
        {{pro_key.name}}
    {% endif %}
{% endblock %}
{% block content %}
<div >
    <div>
        <p style="padding-left:100px;"><a href="{% url 'app1:allProdCat' %}">Home</a>| <a href="{{pro_key.category.get_url}}">{{pro_key.category}}</a>|{{pro_key.name}}</p>

    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
        <div>
            <img class="my_p_image" src="{{pro_key.img.url}}" alt="{{pro_key.name}}">
        </div>
            </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center" >
            <div>
            <h1  class="our">{{pro_key.name}}</h1>
            <div class="my_desc">
            <p class="text-center my_card_text">RS: {{pro_key.price}}</p>
            <p style="text-decoration: underline;">Product Description:</p>
            <p>{{pro_key.desc}}</p>
            </div>
            {% if pro_key.stock <= 0 %}
                <h3 class="my_card_text">Out of Stock</h3>
            {% else %}
            <div style="padding-bottom:50px;">
                <a href="{% url 'cart:add_cart' pro_key.id %}" class="btn btn-primary" >ADD TO CART</a>
                </div>
            {% endif %}
            <br>
        </div>
    </div>
        </div>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  we have variety of products
{% endblock %}

{% block title %}
  search
{% endblock %}

{% block content %}
<div>
    <p class="text-center">
        You have searched for: <b>"{{que1}}"</b>
    </p>
</div>
<div class="container">
      <div class="row">
          {% for i in produ %}
          <div class="col-md-4 my_card">
          <div class="card" style="width: 300px; height:400px; background-color:#F7DC6F">
          <div>
              <div>
                  <a  href="{{i.get_url}}"><img class="card-img-top my_card_img" src="{{i.img.url}}" alt="{{i.name}}"></a>
              </div>
          </div>
          <div class="card-body">

                  <h2 class="card-title my_card_title">{{i.name}}</h2>
                  <p class="card-text my_card_text">RS: {{i.price}}<h6 style="color:green">10% off</h6></p>
              <div>
                  <a href="#" class="btn btn-primary">BUY NOW</a>
                  <a href="{% url 'cart:add_cart' i.id %}" class="btn btn-warning">ADD TO CART</a>
              </div>

          </div>
              {% empty %}
              <div class="row mx-auto">
                  <p class="text-center">0 results found</p>
              </div>
          </div>
          </div>
          {% endfor %}
      </div>
</div>
{% endblock %}